name: CI

on:
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        working-directory: prisma
        run: pnpx prisma generate

      # -------- LINT --------
      - name: Run ESLint
        run: pnpm run eslint

      # -------- PRETTIER --------
      - name: Check formatting with Prettier
        run: pnpm run prettier:check

            # ---- SUPER-LINTER ----
      - name: Run Super-Linter
        uses: super-linter/super-linter@v8.2.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PRETTIER: true
          VALIDATE_ESLINT: true
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_YAML: false
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_MD: false
          VALIDATE_XML: false
          VALIDATE_CSS: false
          VALIDATE_SHELL_SH: false
          VALIDATE_BASH: false
          VALIDATE_PYTHON: false
          VALIDATE_RUBY: false
          VALIDATE_GO: false
          VALIDATE_JAVA: false
          VALIDATE_RUST: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_SQL: false
          VALIDATE_ENV: false
          VALIDATE_CSV: false
          VALIDATE_TERRAFORM: false
          VALIDATE_KUBERNETES: false
          VALIDATE_ANSIBLE: false
          VALIDATE_GITLEAKS: false
          VALIDATE_ARM: false
          VALIDATE_PHP: false
          VALIDATE_PERL: false
          VALIDATE_CLOJURE: false
          VALIDATE_TEXTLINT: false
          VALIDATE_PROTOBUF: false
          VALIDATE_JSCPD: false
          VALIDATE_POWERSHELL: false
          VALIDATE_R: false
          VALIDATE_PLANTUML: false
          VALIDATE_BIOME: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_GRAPHQL_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TRIVY: false
          VALIDATE_CHECKOV: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_GROOVY: false
          VALIDATE_PRE_COMMIT: false
          DISABLE_ERRORS: true
